/********************************************************************
* lreco_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error lreco_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablelreco_dict();
extern void G__cpp_setup_inheritancelreco_dict();
extern void G__cpp_setup_typetablelreco_dict();
extern void G__cpp_setup_memvarlreco_dict();
extern void G__cpp_setup_globallreco_dict();
extern void G__cpp_setup_memfunclreco_dict();
extern void G__cpp_setup_funclreco_dict();
extern void G__set_cpp_environmentlreco_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "DalitzVars.h"
#include "DeltaEMbc.h"
#include "EvtInfo.h"
#include "EvtShape.h"
#include "GammaInfo.h"
#include "GenHepEvt.h"
#include "GenParticleInfo.h"
#include "HamletTag.h"
#include "IPBoost.h"
#include "Ks0Info.h"
#include "Pi0Info.h"
#include "SFWMInfo.h"
#include "TrackInfo.h"
#include "VertexInfo.h"
#include "TrackInfo2.h"
#include "H0Info.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__lreco_dictLN_TClass;
extern G__linked_taginfo G__lreco_dictLN_TBuffer;
extern G__linked_taginfo G__lreco_dictLN_TMemberInspector;
extern G__linked_taginfo G__lreco_dictLN_TObject;
extern G__linked_taginfo G__lreco_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__lreco_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__lreco_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__lreco_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__lreco_dictLN_DalitzVars;
extern G__linked_taginfo G__lreco_dictLN_DeltaEMbc;
extern G__linked_taginfo G__lreco_dictLN_EvtInfo;
extern G__linked_taginfo G__lreco_dictLN_SFWMInfo;
extern G__linked_taginfo G__lreco_dictLN_EvtShape;
extern G__linked_taginfo G__lreco_dictLN_GammaInfo;
extern G__linked_taginfo G__lreco_dictLN_GenHepEvt;
extern G__linked_taginfo G__lreco_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__lreco_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__lreco_dictLN_GenParticleInfo;
extern G__linked_taginfo G__lreco_dictLN_HamletTag;
extern G__linked_taginfo G__lreco_dictLN_IPBoost;
extern G__linked_taginfo G__lreco_dictLN_Ks0Info;
extern G__linked_taginfo G__lreco_dictLN_Pi0Info;
extern G__linked_taginfo G__lreco_dictLN_TrackInfo;
extern G__linked_taginfo G__lreco_dictLN_VertexInfo;
extern G__linked_taginfo G__lreco_dictLN_TrackInfo2;
extern G__linked_taginfo G__lreco_dictLN_H0Info;

/* STUB derived class for protected member access */
